package:
  name: q2-mfa
  version: {{ PLUGIN_VERSION }}

source:
  path: ..

build:
  script: make install

requirements:
  host:
    - pip
    - python {{ python }}
    - setuptools
    - versioningit
    - wheel

  build:
    - python {{ python }}
    - pip
    - setuptools
    - versioningit

  run:
    - bioconductor-mixomics
    - pandas
    - prince-factor-analysis
    - q2-feature-table >={{ q2_feature_table }}
    - q2-metadata >={{ q2_metadata }}
    - q2-types >={{ q2_types }}
    - q2-vizard >={{ q2_vizard }}
    - qiime2 >={{ qiime2 }}
    - rpy2
    - scikit-bio

test:
  requires:
    - parameterized
  imports:
    - q2_mfa
    - qiime2.plugins.mfa
  commands:
    - pytest --pyargs q2_mfa

about:
  home: https://github.com/bokulich-lab/q2-q2_mfa
  license: BSD-3-Clause
  license_family: BSD
